graph LR
  n0["万叔"]
  n1["万叔的"]
  n2["叔的"]
  n3["大家"]
  n4["是万叔"]
  n5["是万"]
  n6["始人"]
  n7["的第"]
  n8["是万叔的"]
  n9["创始人"]
  n10["创始"]
  n11["篇原创"]
  n12["原创"]
  n13["我是"]
  n14["本文"]
  n15["篇原"]
  n16["万叔的第"]
  n17["的时"]
  n18["大家好"]
  n19["家好"]
  n20["文是万叔"]
  n21["本文是万"]
  n22["创始人万"]
  n23["始人万叔"]
  n24["叔的第"]
  n25["人万叔"]
  n26["始人万"]
  n27["阶级"]
  n28["跃迁"]
  n29["的时候"]
  n30["人万"]
  n31["没有"]
  n32["文是万"]
  n33["阶级跃迁"]
  n34["以下"]
  n35["都是"]
  n36["以下是"]
  n37["下是"]
  n38["了一"]
  n39["之前"]
  n17 -- advice:166 --> n29
  n17 -- causal:153 --> n29
  n17 -- contrast:140 --> n29
  n17 -- analogy:71 --> n29
  n0 -- advice:40 --> n1
  n0 -- advice:40 --> n2
  n1 -- advice:40 --> n2
  n0 -- contrast:39 --> n1
  n0 -- contrast:39 --> n2
  n1 -- contrast:39 --> n2
  n0 -- causal:35 --> n1
  n0 -- causal:35 --> n2
  n1 -- causal:35 --> n2
  n0 -- contrast:31 --> n31
  n10 -- causal:29 --> n9
  n10 -- causal:29 --> n6
  n9 -- causal:29 --> n6
  n28 -- contrast:29 --> n27
  n28 -- contrast:28 --> n33
  n27 -- contrast:28 --> n33
  n28 -- causal:27 --> n27
  n28 -- causal:27 --> n33
  n27 -- causal:27 --> n33
  n0 -- contrast:26 --> n5
  n0 -- contrast:26 --> n4
  n5 -- contrast:26 --> n4
  n0 -- advice:25 --> n31
  n0 -- advice:25 --> n17
  n0 -- contrast:25 --> n17
  n0 -- causal:24 --> n31
  n0 -- contrast:23 --> n29
  n28 -- advice:22 --> n27
  n28 -- advice:22 --> n33
  n27 -- advice:22 --> n33
  n28 -- analogy:21 --> n27
  n28 -- analogy:21 --> n33
  n27 -- analogy:21 --> n33
  n0 -- causal:21 --> n17
  n0 -- causal:21 --> n29
  n0 -- analogy:20 --> n1
  n0 -- analogy:20 --> n39
  n0 -- analogy:20 --> n2
  n1 -- analogy:20 --> n2
  n31 -- causal:20 --> n17
  n0 -- advice:19 --> n29
  n31 -- causal:19 --> n29
  n10 -- contrast:19 --> n9
  n10 -- contrast:19 --> n6
  n9 -- contrast:19 --> n6
  n0 -- causal:16 --> n39
  n0 -- causal:16 --> n38
  n0 -- contrast:16 --> n39
  n0 -- advice:15 --> n35
  n10 -- advice:14 --> n9
  n10 -- advice:14 --> n6
  n9 -- advice:14 --> n6
  n3 -- causal:13 --> n35
  n0 -- contrast:12 --> n38
  n17 -- advice:11 --> n35
  n29 -- advice:11 --> n35
  n0 -- causal:11 --> n28
  n39 -- causal:11 --> n31
  n38 -- causal:11 --> n31
  n39 -- contrast:11 --> n31
  n0 -- advice:10 --> n39
  n0 -- analogy:10 --> n17
  n0 -- analogy:10 --> n29
  n0 -- causal:10 --> n35
  n31 -- contrast:10 --> n17
  n0 -- advice:9 --> n38
  n0 -- analogy:9 --> n31
  n0 -- contrast:9 --> n35
  n38 -- contrast:9 --> n31
  n31 -- contrast:9 --> n29
  n31 -- advice:8 --> n35
  n39 -- causal:8 --> n17
  n39 -- causal:8 --> n29
  n31 -- causal:8 --> n35
  n0 -- contrast:8 --> n8
  n1 -- contrast:8 --> n5
  n1 -- contrast:8 --> n4
  n1 -- contrast:8 --> n8
  n2 -- contrast:8 --> n5
  n2 -- contrast:8 --> n4
  n2 -- contrast:8 --> n8
  n5 -- contrast:8 --> n8
  n4 -- contrast:8 --> n8
  n31 -- contrast:8 --> n35
  n31 -- advice:7 --> n17
  n0 -- analogy:7 --> n38
  n0 -- causal:7 --> n27
  n38 -- causal:7 --> n3
  n38 -- causal:7 --> n35
  n17 -- causal:7 --> n35
  n0 -- contrast:7 --> n10
  n0 -- contrast:7 --> n9
  n0 -- contrast:7 --> n6
  n0 -- contrast:7 --> n28
  n39 -- advice:6 --> n17
  n39 -- advice:6 --> n29
  n31 -- advice:6 --> n29
  n10 -- analogy:6 --> n9
  n10 -- analogy:6 --> n6
  n9 -- analogy:6 --> n6
  n29 -- causal:6 --> n35
  n0 -- contrast:6 --> n3
  n39 -- contrast:6 --> n38
  n38 -- contrast:6 --> n17
  n3 -- contrast:6 --> n17
  n0 -- advice:5 --> n3
  n0 -- advice:5 --> n5
  n0 -- advice:5 --> n4
  n3 -- advice:5 --> n35
  n5 -- advice:5 --> n4
  n39 -- analogy:5 --> n17
  n39 -- analogy:5 --> n29
  n0 -- causal:5 --> n5
  n0 -- causal:5 --> n4
  n0 -- causal:5 --> n33
  n38 -- causal:5 --> n17
  n38 -- causal:5 --> n29
  n3 -- causal:5 --> n17
  n5 -- causal:5 --> n4
  n39 -- contrast:5 --> n17
  n39 -- contrast:5 --> n29
  n38 -- contrast:5 --> n3
  n3 -- contrast:5 --> n29
  n31 -- contrast:5 --> n28
  n39 -- advice:4 --> n31
  n38 -- advice:4 --> n31
  n3 -- advice:4 --> n31
  n17 -- advice:4 --> n28
  n3 -- analogy:4 --> n35
  n0 -- causal:4 --> n10
  n0 -- causal:4 --> n9
  n0 -- causal:4 --> n6
  n1 -- causal:4 --> n17
  n1 -- causal:4 --> n29
  n39 -- causal:4 --> n35
  n2 -- causal:4 --> n17
  n2 -- causal:4 --> n29
  n3 -- causal:4 --> n29
  n0 -- contrast:4 --> n27
  n39 -- contrast:4 --> n3
  n39 -- contrast:4 --> n35
  n38 -- contrast:4 --> n29
  n3 -- contrast:4 --> n35
  n17 -- contrast:4 --> n35
  n29 -- contrast:4 --> n35
  n0 -- advice:3 --> n28
  n0 -- advice:3 --> n27
  n0 -- advice:3 --> n33
  n39 -- advice:3 --> n38
  n39 -- advice:3 --> n3
  n39 -- advice:3 --> n35
  n31 -- advice:3 --> n28
  n0 -- analogy:3 --> n28
  n0 -- analogy:3 --> n35
  n0 -- analogy:3 --> n27
  n0 -- analogy:3 --> n33
  n1 -- analogy:3 --> n39
  n39 -- analogy:3 --> n2
  n39 -- analogy:3 --> n31
  n38 -- analogy:3 --> n17
  n38 -- analogy:3 --> n29
  n31 -- analogy:3 --> n17
  n31 -- analogy:3 --> n29
  n31 -- analogy:3 --> n28
  n31 -- analogy:3 --> n27
  n31 -- analogy:3 --> n33
  n39 -- causal:3 --> n38
  n39 -- causal:3 --> n3
  n38 -- causal:3 --> n10
  n38 -- causal:3 --> n9
  n38 -- causal:3 --> n6
  n10 -- causal:3 --> n28
  n10 -- causal:3 --> n27
  n10 -- causal:3 --> n33
  n9 -- causal:3 --> n28
  n9 -- causal:3 --> n27